baseURL: "https://dzx.cz/"
languageCode: "en-US"
title: "Matouš Dzivjak"
author:
  name: "Matouš Dzivjak"
  email: "matousdzivjak@gmail.com"
enableGitInfo: true
enableInlineShortcodes: true
copyright: "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
permalinks:
  posts: /:year-:month-:day/:slug
  books: /:year-:month-:day/:slug
  atoms: /:year-:month-:day/:slug
  photos: /photos/:slug
params:
  description: "Personal website with articles, projects and other work of Matous Dzivjak"
  mainSections: ["books", "posts"]
  math: true
  author:
    name: "Matouš Dzivjak"
    email: "matousdzivjak@gmail.com"
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
    extensions:
      passthrough:
        delimiters:
          block:
          - - '\['
            - '\]'
          - - $$
            - $$
          inline:
          - - '\('
            - '\)'
        enable: true
  highlight:
    noClasses: false
    style: "modus-operandi"
    codeFences: true
  tableOfContents:
    endLevel: 4
    ordered: false
    startLevel: 2
outputFormats:
  rss:
    baseName: rss
    isHTML: false
    isPlainText: false
    mediaType: application/rss+xml
    noUgly: true
    permalinkable: false
    rel: alternate
outputs:
  home:
  - html
  - rss
  section:
  - html
  - rss
menu:
  main:
  - identifier: home
    name: Home
    title: Home
    url: /
    weight: 1
  - identifier: writing
    name: Writing
    title: Writing
    url: /posts/
    weight: 2
  - identifier: reading
    name: Reading
    title: Reading
    url: /books/
    weight: 3
  - identifier: atoms
    name: Atoms
    title: Atoms
    url: /atoms/
    weight: 4
  - identifier: about
    name: About
    title: About
    url: /about/
    weight: 5
  - identifier: gear
    name: Uses
    title: Uses
    url: /uses/
    weight: 6
  - identifier: etc
    name: Etc.
    title: Etc.
    url: /etc/
    weight: 7
  - identifier: photos
    name: Photos
    title: Photos
    url: /photos/
    weight: 8
  - identifier: wiki
    name: Wiki
    url: https://wiki.dzx.cz
    weight: 9
